### ISSUE TITLE
The sidebar doesn't change in case of index pages for each section

### ISSUE THREAD

**Issue by andrii-bodnar** [lorenzolewis/starlight-utils#38]
Hello, I have the following docs structure:

```console
docs
├── apple
│   ├── index.mdx
│   └── introduction.mdx
├── kiwi
│   ├── index.mdx
│   └── introduction.mdx
├── orange
│   ├── index.mdx
│   └── introduction.mdx
└── index.mdx
```

It contains 3 separate sidebars, each of them has an `index` file just to be able to access the section like this: `/apple`, `/kiwi`, `/orange`. It's like a root page for each group.

The sidebar behaves as expected when you open the subpage directly (e.g. `/kiwi/introduction`). But it doesn't change when you navigate to the "root" page for the section.

Each `index.mdx` file has the `sidebar: hidden: true` configuration.

Is it possible to achive the correct sidebar behavior in this case?

Attaching a short video:

https://github.com/lorenzolewis/starlight-utils/assets/29282228/a9245400-5926-4411-ba3a-aacb8d94987e

**Comment by lorenzolewis** [comment]
To confirm: if you DO NOT specify `sidebar > hidden: true` for those index pages does it change as expected? If so, then I'm not sure the combination you've mentioned is something that I would support in Starlight Utils. Each page needs to know which sidebar it belongs to in order to show the correct sidebar. If a page is rendered in NO sidebar then there isn't a way to specify that without a lot of extra logic outside of what's already included in Starlight natively.

**Comment by andrii-bodnar** [comment]
@lorenzolewis thanks for looking into this issue!

Without the `sidebar > hidden: true` it works as expected.

After a few days of working with Starlight and Starlight Utils, I just realized that this use case feels a bit wrong and not natural. So I think we can close this issue.
