### ISSUE TITLE
Request for style options

### ISSUE THREAD

**Issue by quickfold** [lorenzolewis/starlight-utils#61]
Some of my tabs are multi-word/line labels, and others are single word/line. The underlining under the labels does not match vertically, which doesn't look great. I'd like an option to vertically align the lines under the labels. Also, perhaps a full-outline option with rounded corners at the top would also nice, as it would resemble an actual folder tab.

**Comment by lorenzolewis** [comment]
Hi @quickfold ! This is something that should be do-able with custom CSS. For anything that doesn't require changing the structure of the underlying HTML (for example, having a dropdown instead of a horizontal list requires changing the HTML) then I would recommend doing that with CSS directly in your project.

Starlight has some excellent documentation on adding custom CSS here if you haven't already seen it: https://starlight.astro.build/guides/css-and-tailwind/#custom-css-styles

**Comment by quickfold** [comment]
How would I specify that the CSS should apply to the sidebar and only to the top-level labels (the tabs)? I know how to style things like markdown headings, but I don't see any relevant CSS properties in the Starlight `props.css` file on GitHub.
https://github.com/withastro/starlight/blob/main/packages/starlight/style/props.css

**Comment by lorenzolewis** [comment]
If you're specifically looking at the tabs (aka `HorizontalList`) then I would start with the specific file in this repo. Here's a link to the `style` section for it:

https://github.com/lorenzolewis/starlight-utils/blob/0d5817683dca81996ac7fc7ae95735afdf209bdc/packages/starlight-utils/components/HorizontalList.astro#L76-L116


You will most likely need to be a little more specific in your CSS for the scope than what's there since that file is relying on Astro's [Scoped Styles](https://docs.astro.build/en/guides/styling/#scoped-styles) within a component definition. 

```css
starlight-multi-sidebar-tabs .tablist-wrapper {
  /* For styling the container of the whole tab list */
}

starlight-multi-sidebar-tabs ul[role="tablist"] {
  /* For styling the row of the tablets */
}

starlight-multi-sidebar-tabs li.tab {
  /* For styling the container of a single, individual tab */
}

starlight-multi-sidebar-tabs a[role="tab"] {
  /* For styling the link of a single, individual tab */
}

starlight-multi-sidebar-tabs a[role="tab"][aria-selected="true"] {
  /* For styling a selected tab */
}
```

Since these are getting into the implementation details then please bear in mind that there _could_ be breaking changes in future releases (although I try to keep it as stable as possible). So please be sure to test that any custom styles are still working for when updating.

All the best!
