### ISSUE TITLE
Compatibility with i18n?

### ISSUE THREAD

**Issue by BuckyBuck135** [lorenzolewis/starlight-utils#80]
Hi There,
Thanks Lorenzo for creating this plug-in. I would like to use multi-sidebar in my i18n project, but I'm running into an issue.

Given this config:
```JS
export default defineConfig({
	integrations: [
		starlight({
			defaultLocale: 'root', // optional
			locales: {
				// French pages in `src/content/docs`
				root: {
					label: 'Français',
					lang: 'fr',
				},
				// English pages in `src/content/docs/en/`
				en: {
					label: 'English',
					lang: 'en'
				},
			},
			sidebar: [
				{
					label: 'Services',
					link: '/services/',
				},
				{
					label: 'Portfolio',
					link: '/portfolio/',
				},
				{
					label: 'À propos',
					translations: {
						'en': 'About',
					  },
					link: '/about/',
				},
				{
					label: 'Contact',
					link: '/contact/',
				},
				{
					label: 'Blog',
					link: '/blog/',
				},
			],
			plugins: [starlightUtils({
				multiSidebar: {
					switcherStyle: "horizontalList",
				  },
			})],
		}),
	],
});
```

This config works without your plugin, and I'm trying to find a way to create a multi-sidebar with this sidebar object:

```js
	sidebar: [
		{
			label: "Main",
			autogenerate: { directory: "docs" },
		},
		{
			label: "Blog",
			autogenerate: { directory: "blog" },
		},
```

Issue: the "main" group remains empty in the sidebar. This is mostly likely caused by the i18n config and/or my folder structure:
```
src/
----content/
---------docs/
------------------ blog/ // contains .md files
------------------en/ // contains a blog folder, and the same mdx pages as below, in English)
------------------about.mdx
------------------contact.mdx
------------------index.mdx
------------------portfolio.mdx
------------------services.mdx
```

So the question is: how can I configure the multi sidebar so it can handle this i18n structure?

Thank you!
(is it possible to use Starlight in Stackblitz so I can offer a demo?)

**Comment by lorenzolewis** [comment]
Hey @BuckyBuck135 ! This is something that I _believe_ should work because I'm relying on Starlight's logic under the hood to take care of this, but it's very possible that it doesn't. 

Yes, you can do a Starlight repro in Stackblitz 100% If you could provide one with at least the config you're using and a mocked-up folder structure then I can dig in and troubleshoot to see what's happening.

**Comment by BuckyBuck135** [comment]
Hi @lorenzolewis,
Thanks for getting back to me so quickly.
[Here's a repro](https://stackblitz.com/edit/withastro-starlight-ybmubf?file=astro.config.mjs) where I show the empty group, and the various stuff I've tried.

Thanks!

**Comment by lorenzolewis** [comment]
I think this may be a _technical_ gap upstream that is just never hit in production since it wasn't expected to be used in this way with the sidebars. But first, let me state what I understand you're attempting to do to make sure we're on the same page:

- You're expecting 2 groups: "Main" and "Blog"
- For simplicity sake I'll mention blog first: you would expect all the contents under `src/content/docs/blog` and `src/content/docs/en/blog` to show up there, respecting the user's current i18n selection, correct?
- For "Main" are you expecting ONLY `index.mdx` and `contact.mdx` to show up there (ignoring any content in blog)?

For the final point, I see possibly 2 limitations:

1. I can't seem to find a way in Starlight to set an explicit `autogenerate` type for the root directory of a docs folder, that is `src/content/docs`. I've tried things such as `.`, `root`, etc. and can't get any content to generate on the sidebar in non-extended Starlight. Of course, if you leave the sidebar to be IMPLICIT (that is, no `sidebar` object set in the config), then it will generate as expected as it is implied it's in the root. However, that of course doesn't help us with the generation here when we need to explicitly set out sidebars.

2. As for your expectation of the entries in "Main", I don't think you will be able to get what you're expecting given your current folder structure from auto-generation as it's like a glob-style selection. So you will get EVERY entry (including blog entries) in main because you're selecting the folder that contains them all.

Now, all of that being said, I think that limitation 1 isn't a concern here. I see you having 2 options to resolve issue 2 as that won't work in vanilla Starlight, let alone with this plugin:

1. Move all your content you want in your "Main" sidebar to be in a separate directory such as `src/content/docs/pages` or similar. This still allows you to use auto-generated sidebars but will break your links and possibly make the URLs more verbose than you would like.
2. Instead use the (new-ish) shorthand syntax to hand-select the pages you would like to be in that "Main" sidebar. That would look something like this:

```ts
sidebar: [{
        label: 'Main',
        items: ['index', 'contact'],
    },
    {
        label: 'Blog',
        autogenerate: {
            directory: 'blog'
        },
    },
]
```

You can see more on the shorthand here: https://starlight.astro.build/guides/sidebar/#groups

I was able to use the above code in the repro you gave and got the expected i18n-respected sidebar you're after.

Let me know what you think and if that clears it up for you!

**Comment by BuckyBuck135** [comment]
HI @lorenzolewis,
Thanks for taking the time to look at this.
The solution you suggest works perfectly. 

I now realize that `label: 'Main',` does not get translated. It figures because I didn't provide a translation for it. Would that be handled through [translate Starlight's UI?](https://starlight.astro.build/guides/i18n/#translate-starlights-ui)

Cheers.

**Comment by lorenzolewis** [comment]
Nope, that's also directly handled in the config just like you would for a normal sidebar (Starlight doc link: https://starlight.astro.build/guides/sidebar/#internationalization).

For example:

```ts
        {
          label: 'Main',
          translations: {
            'fr': "Principal"
          },
          items: ['index', 'contact'],
        },
```

I'll go ahead and close this because it looks like this is working for you now. Feel free to let me know if you hit any issues along the way!

**Comment by lorenzolewis** [comment]
Oh, and you can also set it directly in the front matter of the page if using the `slug` shorthand (one of the main goals when I made that slug shorthand contribution ;) ): https://starlight.astro.build/reference/frontmatter/#sidebar
